"""

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

"""


def pentagonal_nums(n):
    return (n * (3 * n - 1)) // 2

p = pentagonal_nums
nums = set(pentagonal_nums(i) for i in range(1, 10**5))
l1 = [(p(k), p(j)) for k in range(1, 10**4) for j in range(1, k)
      if p(k) + p(j) in nums and p(k) - p(j) in nums]
print(l1[0][1] - l1[0][0])

